wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/src/main.py
    python_version: 3.11.3
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696252002.356351
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.11.3
      5: 0.15.4
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: train_auroc_step
      5: 1
      6:
      - 1
    - 1: train_f1_step
      5: 1
      6:
      - 1
    - 1: train_precision_step
      5: 1
      6:
      - 1
    - 1: train_recall_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: val_auroc
      5: 1
      6:
      - 1
    - 1: val_f1
      5: 1
      6:
      - 1
    - 1: val_precision
      5: 1
      6:
      - 1
    - 1: val_recall
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    - 1: train_auroc_epoch
      5: 1
      6:
      - 1
    - 1: train_f1_epoch
      5: 1
      6:
      - 1
    - 1: train_precision_epoch
      5: 1
      6:
      - 1
    - 1: train_recall_epoch
      5: 1
      6:
      - 1
